### ISSUE TITLE
`draw_texture()` scale calculation contains incorrect behaviour.

### ISSUE THREAD

**Issue by AuroraEchoes** [Solar-Falcon/rust-raylib#1]
When drawing a texture using `DrawHandle::draw_texture()`, the scale provided in `DrawTextureParams` is multiplied by the source texture (`tex`).

```rs
params.scale.x * tex.width() as f32,
params.scale.y * tex.height() as f32,
```
(*src/drawing.rs:388*)

Since scale is the ratio between the source texture and the destination texture, this behavior is incorrect. For example, my use-case is drawing a single tile from a tile atlas. The total size of the tile atlas should not have a bearing on the sprite's size on the destination texture.

This behavior *should* indicate the ratio between the source texture and the destination texture — `scale = destination /  source`. 

For example, for a 16x16px area from the source texture being transformed onto a 72x72px area, scale should be 4.5x. This is far more intuitive than the current implementation.

**Comment by Solar-Falcon** [comment]
I see the problem. I imagine it was just some sloppy work on my part when I was adding DrawTextureParams, because this is definitely not intended behavior.
Posting the fix here for now. I'll see if there are any more problems with how I use DrawTextureParams and then upload a new version.

```rust
let source = params.source.unwrap_or(Rectangle::new(0., 0., tex.width() as _, tex.height() as _));

unsafe {
    ffi::DrawTexturePro(
        tex.raw.clone(),
        source.into(),
        Rectangle::new(
            position.x,
            position.y,
            params.scale.x * source.width as f32,
            params.scale.y * source.height as f32,
        ).into(),
        params.origin.into(),
        params.rotation,
        params.tint.into(),
    )
}
```

**Comment by AuroraEchoes** [comment]
Thanks so much! I made my own fix in the meantime, so no rush.
